### ISSUE TITLE
Would using try/catch not do what you wanted?

### ISSUE THREAD

**Issue by gep13** [OlegYanushkevich/Cake.SoftNUnit3#2]
Just a quick question...

Would doing something like this:

```
Task("Run-Unit-Tests")
    .IsDependentOn("Build")
    .Does(() =>
{
    try
    {
        NUnit3("./src/**/bin/" + configuration + "/*.Tests.dll", new NUnit3Settings {
            NoResults = true
        });
    }
    catch (System.Exception)
    {
        Information("Some tested failed!");
    }
});
```

Not work for you?  The additional work of processing the results file could be placed in the catch block.

I am just worried about the long term maintenance of this addin, which I must imagine has a lot of duplicated code compared to what already exists in Cake itself.

Would love to talk about this further.

**Comment by gep13** [comment]
@OlegYanushkevich also, I was just wondering, as I happened to notice...

Is this addin a duplicate of this one:

https://www.nuget.org/packages/Cake.NUnit/

**Comment by OlegYanushkevich** [comment]
Thanks, Thanks for information. I can use try/catch block. I'm not sure
that we can use that in cake script.

**Comment by gep13** [comment]
>@OlegYanushkevich said...
I'm not sure
that we can use that in cake script.

You definitely can use a try/catch block in your Cake script.  You can use any "normal" C# syntax within the cake script.

If you try this out, please let me know if this works for you.  It would be great to avoid duplication of effort both in this addin, and potentially the `Cake.NUnit` addin, and instead rely on the native functionality within a script and Cake itself.

**Comment by OlegYanushkevich** [comment]
Yes, It helped me. I marked package as unlisted in nuget.

**Comment by gep13** [comment]
@OlegYanushkevich perfect, glad to hear that it helped!

@Jericho is unlisting of the package in NuGet.org enough to remove it from the Cake.AddinDiscover audit?

**Comment by Jericho** [comment]
@gep13 this addin will be removed from audit when it is not longer return by the Nuget search api. Currently this addin is still included when searching as you can see in this example: https://www.nuget.org/packages?q=Cake.softnunit3

**Comment by gep13** [comment]
@Jericho thanks, that is what I thought.

@OlegYanushkevich you mentioned that you had unlisted the addin on NuGet.org.  Can you confirm what process you followed to do this?  I am still seeing the package as listed (normally a beige banner appears, indicating that it is no longer listed) when looking at the package.  I am wondering if this is a caching issue on NuGet.org, or something else.  Thanks

**Comment by OlegYanushkevich** [comment]
@gep13 maybe is caching issue. Look:
![image](https://user-images.githubusercontent.com/28996736/63323717-28fc1880-c32f-11e9-9286-8aecbbe640c4.png)

**Comment by gep13** [comment]
@OlegYanushkevich indeed, that looks like a caching issue.  Thanks for confirming, I appreciate it!

**Comment by OlegYanushkevich** [comment]
@gep13 thanks for your attention.
